version: '3.8'

services:
  # FastAPI service
  # web:
  #   build: .
  #   container_name: fastapi_app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - es
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
  #     - ELASTICSEARCH_URL=http://es:9200
  #     - KIBANA_URL=http://kibana:5601
  #   networks:
  #     - app-network

  # PostgreSQL database service
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Elasticsearch service
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - "ELASTIC_PASSWORD=changeme"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  # Kibana service
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
    depends_on:
      - es
    networks:
      - app-network

volumes:
  postgres_data:
  es_data:

networks:
  app-network:
    driver: bridge
